# Generated by Django 5.0.7 on 2024-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_tipo_ingresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='utilizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
