# Generated by Django 5.0.7 on 2024-07-13 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ingresso_utilizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to=settings.AUTH_USER_MODEL),
        ),
    ]
