# Generated by Django 5.0.7 on 2024-07-13 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
