# Generated by Django 5.0.7 on 2024-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_pagamento_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('ADMIN', 'Admin')], default='COMUM', max_length=20),
        ),
    ]
