# Generated by Django 5.0.7 on 2024-07-24 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usuario_birthday_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresso',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresso',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='situacao',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('COMPROMETIDO', 'Comprometido(a)')], default='SOLTEIRO', max_length=100),
        ),
    ]
