# Generated by Django 5.0.7 on 2024-07-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_ingresso_data_nascimento_ingresso_nome_ingresso_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='pago',
        ),
    ]
